Fix ➤ CameraActivity
cebroker/emerald-android pull request #144
Opened 2020-11-13 02:15 UTC by EAlexisDuque

```diff
CameraConfig
+ fitToScreen: Boolean

CameraActivity
+ setFitToScreen()
```

2020-11-19 21:08 UTC, lauradelarosa approved these changes

2020-11-19 21:13 UTC, feguerrero commented on app/src/main/java/co/condorlabs/customcomponents/simplecamerax/CameraActivity.kt
> +            if (fitToScreen) setFitToScreen()
The code agreement says don't do that. https://github.com/cebroker/guidelines/blob/master/mobile/AndroidCodeGuideLines.md

2020-11-19 21:35 UTC, lauradelarosa requested changes

2020-11-19 21:35 UTC, lauradelarosa commented on app/src/main/java/co/condorlabs/customcomponents/simplecamerax/CameraActivity.kt
> +    ) {
ca you evaluate if this method can be implemented or deleted, for not violate the segregation interface principle

2020-11-19 21:50 UTC, lauradelarosa approved these changes

2020-11-20 13:03 UTC, feguerrero approved these changes

2020-11-20 13:17 UTC, merged